### PR TITLE
try to build with Android Studio3.0

### PR DESCRIPTION
**Pull request by hannesa2**
Attempt to build with Android Studio 3.0
But I run into this and does someone has a clue what's wrong here ?

`./gradlew buildDependentsNdklibrarysampleX86DebugArmSharedLibrary `

 > :app:compileNdklibrarysampleX86DebugArmSharedLibraryNdklibrarysampleX86DebugArmSharedLibraryMainCpp
> /Users/hannes/git/openCV/OpenCV-AndroidSamples/app/src/main/jni/DetectionBasedTracker.cpp:1:17: fatal error: jni.h: No such file or directory
>  #include <jni.h>
>                  ^
> compilation terminated.
> 
> /Users/hannes/git/openCV/OpenCV-AndroidSamples/app/src/main/jni/Tutorial2.cpp:1:17: fatal error: jni.h: No such file or directory
>  #include <jni.h>
>                  ^
> compilation terminated.
> 
> :app:compileNdklibrarysampleX86DebugArmSharedLibraryNdklibrarysampleX86DebugArmSharedLibraryMainCpp FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileNdklibrarysampleX86DebugArmSharedLibraryNdklibrarysampleX86DebugArmSharedLibraryMainCpp'.
> > Multiple build operations failed.
>       C++ compiler failed while compiling DetectionBasedTracker.cpp.
>       C++ compiler failed while compiling Tutorial2.cpp.
>   See the complete log at: file:///Users/hannes/git/openCV/OpenCV-AndroidSamples/app/build/tmp/compileNdklibrarysampleX86DebugArmSharedLibraryNdklibrarysampleX86DebugArmSharedLibraryMainCpp/output.txt

### CODE REVIEW

**Comment by hannesa2** [comment]
With last commit, I solved previous error, and now I run into this

> /Users/hannes/Development/android-ndk-r10b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: fatal error: --sysroot=: must take a non-empty argument
> collect2: error: ld returned 1 exit status
>
